export const NOTION_ALBUMS_DATABASE_ID = process.env.NOTION_ALBUMS_DATABASE_ID;
export const NOTION_BLOGS_DATABASE_ID = process.env.NOTION_BLOGS_DATABASE_ID;
export const NOTION_PHOTOS_DATABASE_ID = process.env.NOTION_PHOTOS_DATABASE_ID;
export const NOTION_SECRET = process.env.NOTION_SECRET;
